export const getCustomVocab = () => {
    return {
        // Softwares
        logseq: "Software",
        anki: "Software",
        obsidian: "Software",
        notion: "Software",
        jira: "Software",
        confluence: "Software",
        amplenote: "Software",
        tana: "Software",
        siyuan: "Software",
        joplin: "Software",
        simplenotes: "Software",
        standardnotes: "Software",
        heptabase: "Software",
        "roam research": "Software",
        evernote: "Software",
        onenote: "Software",
        bear: "Software",
        zettelkasten: "Software",
        craft: "Software",
        remnote: "Software",
        workflowy: "Software",
        dendron: "Software",
        capacities: "Software",
        typora: "Software",
        foam: "Software",
        mem: "Software",
        reflect: "Software",
        devonthink: "Software",

        // Technical terms
        db: "TechnicalTerm",
        file: "TechnicalTerm",
        plugin: "TechnicalTerm",
        database: "TechnicalTerm",
        version: "TechnicalTerm",
        graph: "TechnicalTerm",
        edn: "TechnicalTerm",
        markdown: "TechnicalTerm",
        "org-mode": "TechnicalTerm",
        metadata: "TechnicalTerm",
        config: "TechnicalTerm",
        query: "TechnicalTerm",
        queries: "TechnicalTerm",
        datalog: "TechnicalTerm",
        datascript: "TechnicalTerm",
        pages: "TechnicalTerm",
        block: "TechnicalTerm",
        "simple query": "TechnicalTerm",
        "advanced query": "TechnicalTerm",
        clojure: "TechnicalTerm",
        sync: "TechnicalTerm",
        git: "TechnicalTerm",
        encryption: "TechnicalTerm",
        vault: "TechnicalTerm",

        // Features
        sidebar: "Feature",
        whiteboard: "Feature",
        flashcards: "Feature",
        journals: "Feature",
        hierarchy: "Feature",
        properties: "Feature",
        aliases: "Feature",
        namespace: "Feature",

        // Social Platforms
        discord: "Software",
        telegram: "Software",
        twitter: "Software",
        tweet: "Feature",
        mail: "Software",
        proton: "Software",
        gmail: "Software",
        yahoo: "Software",
        bitcoin: "Software",
        facebook: "Software",
        instagram: "Software",
        reddit: "Software",
        linkedin: "Software",
        youtube: "Software",
        tiktok: "Software",
        whatsapp: "Software",
        signal: "Software",
        wechat: "Software",
        slack: "Software",
        mastodon: "Software",
        threads: "Software",
        pinterest: "Software",
        snapchat: "Software",
        quora: "Software",
        medium: "Software",
        substack: "Software",
        viber: "Software",
        line: "Software",
        tinder: "Software",
        bumble: "Software",
        hinge: "Software",
        okcupid: "Software",
        grindr: "Software",
        match: "Software",
        eharmony: "Software",
        "coffee meets bagel": "Software",
        badoo: "Software",
        zoosk: "Software",

        // Newsletter / Blog Platforms
        beehiiv: "Software",
        ghost: "Software",
        revue: "Software",
        mailchimp: "Software",
        convertkit: "Software",
        "kit": "Software",
        wordpress: "Software",
        blogger: "Software",
        newsletter: "Feature",
        blog: "Feature",
        rss: "Feature",
        feed: "Feature",
        podcast: "Feature",

        // Student / Academic
        study: "Feature",
        exam: "Feature",
        quiz: "Feature",
        lecture: "Feature",
        assignment: "Feature",
        coursework: "Feature",
        semester: "Feature",
        syllabus: "Feature",
        thesis: "Feature",
        dissertation: "Feature",
        citation: "Feature",
        bibliography: "Feature",
        transcript: "Feature",
        gpa: "Feature",
        scholarship: "Feature",
        financialaid: "Feature",
        tuition: "Feature",
        textbook: "Feature",
        graduation: "Feature",
        "peer review": "Feature",
        lab: "Feature",
        tutorial: "Feature",
        cohort: "Feature",
        zotero: "Software",
        mendeley: "Software",
        overleaf: "Software",
        grammarly: "Software",
        quizlet: "Software",
        chegg: "Software",
        coursera: "Software",
        udemy: "Software",
        "khan academy": "Software",
        edx: "Software",
        duolingo: "Software",
        canvas: "Software",
        blackboard: "Software",
        moodle: "Software",
        "google classroom": "Software",
        jstor: "Software",
        sciencedirect: "Software",

        // Research-specific
        methodology: "Feature",
        hypothesis: "Feature",
        "literature review": "Feature",
        abstract: "Feature",
        "systematic review": "Feature",
        "scoping review": "Feature",
        "meta-analysis": "Feature",
        "research question": "Feature",
        dataset: "Feature",
        preprint: "Feature",
        replication: "Feature",
        qualitative: "Feature",
        quantitative: "Feature",
        "p-value": "Feature",
        regression: "Feature",
        correlation: "Feature",
        "null hypothesis": "Feature",
        manuscript: "Feature",
        publication: "Feature",
        journal: "Feature",
        conference: "Feature",
        proceedings: "Feature",
        "impact factor": "Feature",
        "h-index": "Feature",
        "open access": "Feature",
        grant: "Feature",
        fellowship: "Feature",
        postdoctoral: "Feature",
        doctorate: "Feature",
        arxiv: "Software",
        "google scholar": "Software",
        pubmed: "Software",
        "semantic scholar": "Software",
        researchgate: "Software",
        "academia.edu": "Software",
        orcid: "Software",
        doi: "Software",
        scopus: "Software",
        "web of science": "Software",

        // Video Platforms
        vimeo: "Software",
        twitch: "Software",
        netflix: "Software",
        hulu: "Software",
        "disney+": "Software",
        "prime video": "Software",
        "hbo max": "Software",
        peacock: "Software",
        dailymotion: "Software",
        crunchyroll: "Software",
        bilibili: "Software",
        iqiyi: "Software",
        youku: "Software",
        kick: "Software",
        rumble: "Software",
        odysee: "Software",
        vevo: "Software",
        wistia: "Software",
        roku: "Software",

        // AI Tools
        chatgpt: "Software",
        claude: "Software",
        gemini: "Software",
        perplexity: "Software",
        copilot: "Software",
        midjourney: "Software",
        "stable diffusion": "Software",
        grok: "Software",
        llama: "Software",
        "hugging face": "Software",
        ollama: "Software",

        // Cloud & Productivity
        "google drive": "Software",
        dropbox: "Software",
        onedrive: "Software",
        box: "Software",
        icloud: "Software",
        "google docs": "Software",
        "google sheets": "Software",
        "google slides": "Software",
        "microsoft 365": "Software",
        "google calendar": "Software",
        "notion calendar": "Software",
        calendly: "Software",
        zoom: "Software",
        "google meet": "Software",
        webex: "Software",
        figma: "Software",
        miro: "Software",
        trello: "Software",
        asana: "Software",
        "basecamp": "Software",

        // Music & Audio
        spotify: "Software",
        "apple music": "Software",
        soundcloud: "Software",
        tidal: "Software",
        pandora: "Software",
        deezer: "Software",
        bandcamp: "Software",
        audible: "Software",
        podcasts: "Feature",

        // Gaming
        steam: "Software",
        "epic games": "Software",
        playstation: "Software",
        xbox: "Software",
        nintendo: "Software",
        roblox: "Software",
        "ea": "Software",
        "battle.net": "Software",

        // Shopping & E-commerce
        amazon: "Software",
        ebay: "Software",
        etsy: "Software",
        shopify: "Software",
        aliexpress: "Software",
        walmart: "Software",
        temu: "Software",
        "best buy": "Software",
        "wish": "Software",

        // Finance & Crypto
        paypal: "Software",
        venmo: "Software",
        stripe: "Software",
        coinbase: "Software",
        binance: "Software",
        "robinhood": "Software",
        "ethereum": "Software",
        "solana": "Software",
        "blockchain": "Feature",
        "credit card": "Feature",
        "mortgage": "Feature",
        "investment": "Feature",

        // Books & Reading
        kindle: "Software",
        goodreads: "Software",
        libby: "Software",
        "google books": "Software",
        "apple books": "Software",

        // Health & Fitness
        fitbit: "Software",
        strava: "Software",
        "myfitnesspal": "Software",
        whoop: "Software",
        peloton: "Software",
        "apple health": "Software",
        "calm": "Software",
        "headspace": "Software",

        // Developer Tools
        github: "Software",
        gitlab: "Software",
        bitbucket: "Software",
        docker: "Software",
        kubernetes: "Software",
        aws: "Software",
        "google cloud": "Software",
        azure: "Software",
        vercel: "Software",
        "netlify": "Software",
        "vscode": "Software",
        "stack overflow": "Software",
        "npm": "Software",
        "postman": "Software",

        // News & Media
        cnn: "Software",
        bbc: "Software",
        "new york times": "Software",
        reuters: "Software",
        bloomberg: "Software",
        "the verge": "Software",
        techcrunch: "Software",
        hackernews: "Software",

        // Travel & Maps
        "google maps": "Software",
        waze: "Software",
        airbnb: "Software",
        booking: "Software",
        expedia: "Software",
        uber: "Software",
        lyft: "Software",
        "tripadvisor": "Software",

        // Job & Career
        indeed: "Software",
        glassdoor: "Software",
        "monster": "Software",
        "ziprecruiter": "Software",
        "resume": "Feature",
        "interview": "Feature",
        "cover letter": "Feature",

        // Password & Security
        "1password": "Software",
        bitwarden: "Software",
        lastpass: "Software",
        "nordvpn": "Software",
        "expressvpn": "Software",

        // Math Jargon
        theorem: "TechnicalTerm",
        lemma: "TechnicalTerm",
        corollary: "TechnicalTerm",
        proof: "TechnicalTerm",
        integral: "TechnicalTerm",
        derivative: "TechnicalTerm",
        matrix: "TechnicalTerm",
        vector: "TechnicalTerm",
        "eigenvalue": "TechnicalTerm",
        "eigenvector": "TechnicalTerm",
        polynomial: "TechnicalTerm",
        calculus: "TechnicalTerm",
        algebra: "TechnicalTerm",
        geometry: "TechnicalTerm",
        topology: "TechnicalTerm",
        manifold: "TechnicalTerm",
        tensor: "TechnicalTerm",
        probability: "TechnicalTerm",
        statistics: "TechnicalTerm",
        distribution: "TechnicalTerm",
        algorithm: "TechnicalTerm",
        complexity: "TechnicalTerm",
        "graph theory": "TechnicalTerm",
        "group theory": "TechnicalTerm",
        "set theory": "TechnicalTerm",
        function: "TechnicalTerm",
        limit: "TechnicalTerm",
        convergence: "TechnicalTerm",
        "differential equation": "TechnicalTerm",
        "linear algebra": "TechnicalTerm",
        combinatorics: "TechnicalTerm",
        "number theory": "TechnicalTerm",
        fractal: "TechnicalTerm",
        gradient: "TechnicalTerm",
        optimization: "TechnicalTerm",
        bayesian: "TechnicalTerm",
        markov: "TechnicalTerm",
        stochastic: "TechnicalTerm",

        // Biology Jargon
        cell: "TechnicalTerm",
        gene: "TechnicalTerm",
        genome: "TechnicalTerm",
        dna: "TechnicalTerm",
        rna: "TechnicalTerm",
        protein: "TechnicalTerm",
        enzyme: "TechnicalTerm",
        mitosis: "TechnicalTerm",
        meiosis: "TechnicalTerm",
        chromosome: "TechnicalTerm",
        mutation: "TechnicalTerm",
        allele: "TechnicalTerm",
        phenotype: "TechnicalTerm",
        genotype: "TechnicalTerm",
        ecosystem: "TechnicalTerm",
        species: "TechnicalTerm",
        evolution: "TechnicalTerm",
        "natural selection": "TechnicalTerm",
        photosynthesis: "TechnicalTerm",
        metabolism: "TechnicalTerm",
        mitochondria: "TechnicalTerm",
        ribosome: "TechnicalTerm",
        nucleus: "TechnicalTerm",
        organelle: "TechnicalTerm",
        peptide: "TechnicalTerm",
        "amino acid": "TechnicalTerm",
        nucleotide: "TechnicalTerm",
        codon: "TechnicalTerm",
        transcription: "TechnicalTerm",
        translation: "TechnicalTerm",
        "stem cell": "TechnicalTerm",
        neuron: "TechnicalTerm",
        synapse: "TechnicalTerm",
        antibody: "TechnicalTerm",
        antigen: "TechnicalTerm",
        virus: "TechnicalTerm",
        bacteria: "TechnicalTerm",
        eukaryotic: "TechnicalTerm",
        prokaryotic: "TechnicalTerm",
        taxonomy: "TechnicalTerm",
        ecology: "TechnicalTerm",
        biodiversity: "TechnicalTerm",
        symbiosis: "TechnicalTerm",
        apoptosis: "TechnicalTerm",
        homeostasis: "TechnicalTerm",
        hormone: "TechnicalTerm",
        receptor: "TechnicalTerm",
        ligand: "TechnicalTerm",
        osmosis: "TechnicalTerm",
        diffusion: "TechnicalTerm",

        // Science Jargon (Physics / Chemistry)
        atom: "TechnicalTerm",
        molecule: "TechnicalTerm",
        electron: "TechnicalTerm",
        neutron: "TechnicalTerm",
        quantum: "TechnicalTerm",
        relativity: "TechnicalTerm",
        entropy: "TechnicalTerm",
        thermodynamics: "TechnicalTerm",
        reaction: "TechnicalTerm",
        catalyst: "TechnicalTerm",
        acid: "TechnicalTerm",
        base: "TechnicalTerm",
        isotope: "TechnicalTerm",
        element: "TechnicalTerm",
        compound: "TechnicalTerm",
        force: "TechnicalTerm",
        energy: "TechnicalTerm",
        momentum: "TechnicalTerm",
        velocity: "TechnicalTerm",
        acceleration: "TechnicalTerm",
        gravity: "TechnicalTerm",
        radiation: "TechnicalTerm",
        fusion: "TechnicalTerm",
        fission: "TechnicalTerm",
        particle: "TechnicalTerm",
        wavelength: "TechnicalTerm",
        spectrum: "TechnicalTerm",
        electromagnetism: "TechnicalTerm",

        // Tech Software (IDEs, Editors, Infra)
        intellij: "Software",
        pycharm: "Software",
        webstorm: "Software",
        rider: "Software",
        "android studio": "Software",
        xcode: "Software",
        "sublime text": "Software",
        "atom editor": "Software",
        vim: "Software",
        neovim: "Software",
        emacs: "Software",
        eclipse: "Software",
        "visual studio": "Software",
        "notepad++": "Software",
        jetbrains: "Software",
        cursor: "Software",
        jupyter: "Software",
        "jupyter notebook": "Software",
        colab: "Software",
        anaconda: "Software",
        terraform: "Software",
        ansible: "Software",
        jenkins: "Software",
        circleci: "Software",
        "github actions": "Software",
        gitkraken: "Software",
        sourcetree: "Software",
        homebrew: "Software",
        nginx: "Software",
        apache: "Software",
        kafka: "Software",
        rabbitmq: "Software",
        elasticsearch: "Software",
        redis: "Software",
        postgres: "Software",
        mongodb: "Software",
        mysql: "Software",
        sqlite: "Software",
        supabase: "Software",
        firebase: "Software",
        grafana: "Software",
        datadog: "Software",
        prometheus: "Software",

        // Programming Languages
        python: "TechnicalTerm",
        typescript: "TechnicalTerm",
        javascript: "TechnicalTerm",
        rust: "TechnicalTerm",
        golang: "TechnicalTerm",
        java: "TechnicalTerm",
        kotlin: "TechnicalTerm",
        swift: "TechnicalTerm",
        scala: "TechnicalTerm",
        ruby: "TechnicalTerm",
        php: "TechnicalTerm",
        haskell: "TechnicalTerm",
        cpp: "TechnicalTerm",

        // Frameworks & Libraries
        react: "TechnicalTerm",
        vue: "TechnicalTerm",
        angular: "TechnicalTerm",
        svelte: "TechnicalTerm",
        "next.js": "TechnicalTerm",
        node: "TechnicalTerm",
        deno: "TechnicalTerm",
        bun: "TechnicalTerm",
        tailwind: "TechnicalTerm",
        django: "TechnicalTerm",
        flask: "TechnicalTerm",
        fastapi: "TechnicalTerm",
        spring: "TechnicalTerm",
        dotnet: "TechnicalTerm",
        pytorch: "TechnicalTerm",
        tensorflow: "TechnicalTerm",
        keras: "TechnicalTerm",
        "scikit-learn": "TechnicalTerm",
        pandas: "TechnicalTerm",
        numpy: "TechnicalTerm",
        matplotlib: "TechnicalTerm",

        // Operating Systems & Shells
        linux: "TechnicalTerm",
        ubuntu: "TechnicalTerm",
        debian: "TechnicalTerm",
        fedora: "TechnicalTerm",
        arch: "TechnicalTerm",
        macos: "TechnicalTerm",
        windows: "TechnicalTerm",
        bash: "TechnicalTerm",
        zsh: "TechnicalTerm",
        powershell: "TechnicalTerm",

    };
};