name: Deploy Docusaurus to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Success"
